In [ ]:
import numpy as np

# Generating  a random vector of size 15 with integers in the range 1-20
random_vector = np.random.randint(1, 21, 15) # here we are using the randint function to find the random vector

# a. Reshaping  the array to 3 by 5
reshaped_array = random_vector.reshape(3, 5)

# b. Print array shape
print("Original random vector shape:", random_vector.shape)
print("Reshaped array shape:", reshaped_array.shape)

# c. Replacing  the max value in the reshaped array with a particular  value (e.g., 99)
max_value = np.max(reshaped_array)
reshaped_array[reshaped_array == max_value] = 99

print("Reshaped array with max replaced:")
print(reshaped_array)



Original random vector shape: (15,)
Reshaped array shape: (3, 5)
Reshaped array with max replaced:
[[ 6  9 13 11  9]
 [17  3  8 12 11]
 [13  8  4 99  7]]


In [14]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],dtype=np.int32)

print(type(a),a.shape,a.dtype)  # printing the type,shape and datatype of array

<class 'numpy.ndarray'> (4, 3) int32


In [ ]:
import numpy as np

# given the array
array = np.array([[0, 1, 2],
                  [3, 4, 5]])

# caluclating  the sum of diagonal elements
dg_sum = np.trace(array) # using the trace function

# Print the sum of diagonal elements
print("Sum of diagonal elements:", dg_sum)


Sum of diagonal elements: 4


In [ ]:
import numpy as np

# Creating  an array of even numbers between 10 and 70
even_array = np.arange(10, 71, 2) # we used the slicing technique

# Similarly  Creating  an array of odd numbers between 10 and 70
odd_array = np.arange(11, 71, 2)

print("Even numbers array:", even_array)
print("Odd numbers array:", odd_array)

# Creating two arrays of the same size
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Performing element-wise addition
result_addition = array1 + array2

# Performing element-wise subtraction
result_subtraction = array1 - array2

# Performing element-wise multiplication
result_multiplication = array1 * array2

print("Element-wise addition:", result_addition)
print("Element-wise subtraction:", result_subtraction)
print("Element-wise multiplication:", result_multiplication)


# Define the array
array = np.array([[5.54, 3.38, 7.99],
                  [3.54, 4.38, 6.99],
                  [1.54, 2.39, 9.29]])

# Sort by row in ascending order
sorted_by_row = np.sort(array, axis=1) # with axis is 1 it sorts along row

# Sort by column in ascending order
sorted_by_column = np.sort(array, axis=0) # with axis is 0 it sorts along column

print("Sorted by row:")
print(sorted_by_row)

print("Sorted by column:")
print(sorted_by_column)



Even numbers array: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70]
Odd numbers array: [11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57
 59 61 63 65 67 69]
Element-wise addition: [5 7 9]
Element-wise subtraction: [-3 -3 -3]
Element-wise multiplication: [ 4 10 18]
Sorted by row:
[[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
Sorted by column:
[[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]


In [15]:
import numpy as np

# Create the array with missing data (nan)
array = np.array([[4, 2, np.nan, 1],
                  [11, 12, 14, 9],
                  [5, np.nan, 1, np.nan]])

# Find missing data and return a Boolean array
missing_data = np.isnan(array) #used to find the missing data and return true or flase

# Print the Boolean array
print("Missing Data (True/False):")
print(missing_data)


Missing Data (True/False):
[[False False  True False]
 [False False False False]
 [False  True False  True]]
